# This is a basic workflow to help you get started with Actions

name: Website check

on:
  schedule:
    - cron: '15 * * * *'

jobs:
  ping_site:
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
    - name: Check the web site
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://www.clafeed.de/"
        expected-statuses: "200,301"
    - name: Check the app site
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://app.clafeed.de/"
        expected-statuses: "200,301"
